feat: added stats module
vitaliibredun/java-explore-with-me pull request #3
Opened 2023-04-26 19:58 UTC by vitaliibredun

2023-04-27 10:22 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-04-27 10:22 UTC, ErkinKasymaliev commented on docker-compose.yml
> +#  ewm-db:
это надо раскомментить

2023-04-27 10:22 UTC, ErkinKasymaliev commented on docker-compose.yml
> +#  ewm-service:
это надо раскомментить, а в main-service должен быть пустой проект с
@SpringBootApplication
public class MainService

2023-04-27 10:22 UTC, ErkinKasymaliev commented on stats/stats-server/src/test/java/ru/practicum/ewm/StatsControllerTests.java
> +//                .andExpect(jsonPath("size()", is(expectedSize)))
закомментированный код оставлять не надо

2023-04-27 10:22 UTC, ErkinKasymaliev commented on stats/stats-server/src/main/java/ru/practicum/ewm/service/StatsServiceImpl.java
> +        boolean allStats = uris == null && unique.equals("false");
зачем все эти проверки? можно же required=true в контроллере @RequestParam(value = "uris", required = true)

2023-04-27 16:22 UTC, vitaliibredun commented on stats/stats-server/src/main/java/ru/practicum/ewm/service/StatsServiceImpl.java
> +        boolean allStats = uris == null && unique.equals("false");
привет
тут к сожалению не могу так реализовать, так как по документации open API и тестам в postman у нас параметры uris и unique не обязательные

2023-04-28 08:07 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-04-28 10:02 UTC, vitaliibredun commented
> привет, работа принята

привет
спасибо большое  💪

2023-04-28 10:03 UTC, merged