feat: added main module
vitaliibredun/java-explore-with-me pull request #4
Opened 2023-05-09 17:03 UTC by vitaliibredun

2023-05-11 04:38 UTC, ErkinKasymaliev requested changes
привет, оставил комменты.
также check-s слетели, обязательно их поправьте

2023-05-11 04:38 UTC, ErkinKasymaliev commented on stats/stats-client/src/main/java/ru/practicum/ewm/StatsClient.java
> +    @Value("http://localhost:9090")
зачем удалили? было же правильно

2023-05-11 04:38 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/ewm/category/service/CategoryServiceImpl.java
> +        boolean noName = categoryDto.getName() == null;
а почему бы не поставить аннотации в dto для валидации?

2023-05-11 04:38 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/ewm/category/service/CategoryServiceImpl.java
> +    private Category doUpdate(Category oldCategory, Category newCategory) {
бесполезный метод, лучше удалите

2023-05-11 04:38 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/ewm/category/service/CategoryServiceImpl.java
> +    private Category checkCategoryExist(Long catId) {
смотрите коммент выше, используется один раз, и в ней несложная логика, нет смысла выносить в отдельный метод

2023-05-11 04:38 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/ewm/compilation/service/CompilationServiceImpl.java
> +        boolean eventsIsNull = compilationDto.getEvents() == null;
лучше аннотациями проверять

2023-05-11 04:38 UTC, ErkinKasymaliev commented on main-service/src/main/resources/application.properties
> +DB_NAME=explore-main
это прописывается в docker-compose

2023-05-11 04:38 UTC, ErkinKasymaliev commented on stats/stats-server/src/main/resources/application.properties
> +DB_NAME=explore-stats
это прописывается в docker-compose

2023-05-11 07:48 UTC, vitaliibredun commented on main-service/src/main/java/ru/practicum/ewm/category/service/CategoryServiceImpl.java
> +        boolean noName = categoryDto.getName() == null;
спасибо) я постоянно забываю о их существовании и пишу дополнительные проверки лишние)

2023-05-11 07:58 UTC, vitaliibredun commented on main-service/src/main/java/ru/practicum/ewm/category/service/CategoryServiceImpl.java
> +    private Category doUpdate(Category oldCategory, Category newCategory) {
согласен, спасибо
я тут что-то загнался)

2023-05-11 08:01 UTC, vitaliibredun commented on main-service/src/main/java/ru/practicum/ewm/compilation/service/CompilationServiceImpl.java
> +        boolean eventsIsNull = compilationDto.getEvents() == null;
спасибо, я реально забываю и делаю лишнее)

2023-05-11 08:12 UTC, ErkinKasymaliev commented on stats/stats-client/src/main/java/ru/practicum/ewm/StatsClient.java
> +    @Value("http://localhost:9090")
stats-server.url в application.properties должен быть прописан

2023-05-11 08:14 UTC, vitaliibredun commented on main-service/src/main/resources/application.properties
> +DB_NAME=explore-main
да, конечно, в docker-compose так же прописал, просто когда запускаю локально приложение вне докер контейнеров, приходится дополнительный код держать в где прописаны названия чтобы подключиться к БД, поэтому такое решение

2023-05-11 20:04 UTC, vitaliibredun commented on stats/stats-client/src/main/java/ru/practicum/ewm/StatsClient.java
> +    @Value("http://localhost:9090")
да, так и было, не пойму почему не работает 
и сегодня поковырялся, в сети тоже поискал, ничего не нахожу по ошибке в моём случае
выскакивает Could not resolve placeholder 'stats-server.url' in value "${stats-server.url}"

хотя файл application.properties находится на своём месте и определён как resource в модуле
не понимаю что не так
поэтому уже решил так прописывать полный путь сразу в аннотации

2023-05-14 07:32 UTC, ErkinKasymaliev approved these changes
привет, работа принята!
Но перед мержом поправьте комменты и проверьте еще раз сборку

2023-05-14 07:32 UTC, ErkinKasymaliev commented on stats/stats-client/src/main/resources/application.properties
>  logging.level.org.springframework.web.client.RestTemplate=DEBUG
отсюда удалите resources

2023-05-14 07:32 UTC, ErkinKasymaliev commented on stats/stats-client/src/main/java/ru/practicum/ewm/StatsClient.java
> +    @Value("http://stats-server:9090")
верните @Value("${stats-server.url}"), но пропишите так @Value("${stats-server.url:http://localhost:9090}") и добавьте stats-server.url в application.properties в пакете main-service добавьте

2023-05-14 08:25 UTC, vitaliibredun commented on main-service/src/main/resources/application.properties
> +DB_NAME=explore-main
понял, спасибо, поправлю

2023-05-14 08:42 UTC, vitaliibredun commented on stats/stats-client/src/main/java/ru/practicum/ewm/StatsClient.java
> +    @Value("http://stats-server:9090")
спасибо большое
я думал что ссылку stats-server.url нужно хранить в application.properties в директории клиента

2023-05-14 10:04 UTC, merged